#NP service
apiVersion: v1
kind: Service
metadata:
  name: addressbok-np
  labels:
    app: addressbook
spec:
  selector:
    app: addressbook
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deploy
  labels:
    app: addressbook
    tier: "fe-and-be"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook-cont
        image: vivekgupta434/addressbook-jnkns-dkr:1
---
