apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    app: wordpress
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /k8-pv-dir/pv-50-gib/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: use
          operator: In
          values:
          - storage-server
