apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-test-pv
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 7Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/k8-pv-dir
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - hdd
