apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  namespace: default
spec:
  containers:
  - name: nginx-cont
    image: nginx:1.17
  tolerations:
  - key: app
    operator: Equal
    value: nginx
    effect: NoSchedule
