apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  namespace: default
  labels:
    sch: node-affinity
spec:
  containers:
  - name: nginx-cont
    image: nginx:1.16
  - name: redis-cont
    image: redis
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: mem
            operator: In
            values: 
            - '8'
          - key: cpu
            operator: In
            values: 
            - '4'
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: storage
            operator: In
            values: 
            - hdd
