apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
  namespace: default
spec:
  containers:
  - name: redis-cont
    image: redis
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - nginx
        topologyKey: "kubernetes.io/hostname"
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - database
        topologyKey: "kubernetes.io/hostname"
