# Create a PVC of 20 gb
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: db-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
---

# create a ClusterIP service

apiVersion: v1
kind: Service
metadata: 
  name: db-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: wordpress
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
    
# create a deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: wordpress
    tier: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wordpress
      tier: db
  template:
    metadata:
      labels:
        app: wordpress
        tier: db
    spec:
      containers:
      - name: db-container
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root-pass
        ports:
        - containerPort: 3306
          name: mysql-port
        
